var annotated_dup =
[
    [ "Catch", "d4/d13/namespace_catch.html", "d4/d13/namespace_catch" ],
    [ "CliParser", "db/dc2/namespace_cli_parser.html", "db/dc2/namespace_cli_parser" ],
    [ "tinyxml2", "da/dce/namespacetinyxml2.html", "da/dce/namespacetinyxml2" ],
    [ "AbsFunc", "dd/d1e/class_abs_func.html", "dd/d1e/class_abs_func" ],
    [ "ArgFunc", "d8/d80/class_arg_func.html", "d8/d80/class_arg_func" ],
    [ "Catch_global_namespace_dummy", "d5/df8/struct_catch__global__namespace__dummy.html", null ],
    [ "CLI", "dc/dfb/class_c_l_i.html", "dc/dfb/class_c_l_i" ],
    [ "CliFunc", "d2/dba/struct_cli_func.html", "d2/dba/struct_cli_func" ],
    [ "Complex", "d4/d59/struct_complex.html", "d4/d59/struct_complex" ],
    [ "ConjFunc", "d6/d1d/class_conj_func.html", "d6/d1d/class_conj_func" ],
    [ "CosFunc", "d5/db0/class_cos_func.html", "d5/db0/class_cos_func" ],
    [ "CoshFunc", "d0/d7d/class_cosh_func.html", "d0/d7d/class_cosh_func" ],
    [ "CreditsFunc", "db/de5/class_credits_func.html", "db/de5/class_credits_func" ],
    [ "EulerPrintFunc", "dc/d55/class_euler_print_func.html", "dc/d55/class_euler_print_func" ],
    [ "ExpFunc", "d9/dc0/class_exp_func.html", "d9/dc0/class_exp_func" ],
    [ "Exponential", "df/d67/struct_exponential.html", "df/d67/struct_exponential" ],
    [ "HelpFunc", "d7/d62/class_help_func.html", "d7/d62/class_help_func" ],
    [ "ImagFunc", "d1/de7/class_imag_func.html", "d1/de7/class_imag_func" ],
    [ "Log10Func", "d7/d48/class_log10_func.html", "d7/d48/class_log10_func" ],
    [ "LogFunc", "de/d5e/class_log_func.html", "de/d5e/class_log_func" ],
    [ "NormFunc", "dd/d09/class_norm_func.html", "dd/d09/class_norm_func" ],
    [ "PowFunc", "db/da7/class_pow_func.html", "db/da7/class_pow_func" ],
    [ "PrintFunc", "d1/d3b/class_print_func.html", "d1/d3b/class_print_func" ],
    [ "QuitFunc", "d6/d36/class_quit_func.html", "d6/d36/class_quit_func" ],
    [ "RealFunc", "d0/da5/class_real_func.html", "d0/da5/class_real_func" ],
    [ "SinFunc", "d4/d8d/class_sin_func.html", "d4/d8d/class_sin_func" ],
    [ "SinhFunc", "df/d2f/class_sinh_func.html", "df/d2f/class_sinh_func" ],
    [ "SqrtFunc", "d1/d22/class_sqrt_func.html", "d1/d22/class_sqrt_func" ],
    [ "TanFunc", "da/df5/class_tan_func.html", "da/df5/class_tan_func" ],
    [ "TanhFunc", "d5/d2a/class_tanh_func.html", "d5/d2a/class_tanh_func" ],
    [ "widthbuf", "dc/d88/classwidthbuf.html", "dc/d88/classwidthbuf" ],
    [ "widthstream", "d9/d67/classwidthstream.html", "d9/d67/classwidthstream" ],
    [ "XmlCommandLogger", "d8/d60/class_xml_command_logger.html", "d8/d60/class_xml_command_logger" ]
];