#pragma once

#include "CliFuncs/AbsFunc.hpp"
#include "CliFuncs/ArgFunc.hpp"
#include "CliFuncs/ConjFunc.hpp"
#include "CliFuncs/CosFunc.hpp"
#include "CliFuncs/CoshFunc.hpp"
#include "CliFuncs/ExpFunc.hpp"
#include "CliFuncs/ImagFunc.hpp"
#include "CliFuncs/Log10Func.hpp"
#include "CliFuncs/LogFunc.hpp"
#include "CliFuncs/NormFunc.hpp"
#include "CliFuncs/PowFunc.hpp"
#include "CliFuncs/RealFunc.hpp"
#include "CliFuncs/SinFunc.hpp"
#include "CliFuncs/SinhFunc.hpp"
#include "CliFuncs/SqrtFunc.hpp"
#include "CliFuncs/TanFunc.hpp"
#include "CliFuncs/TanhFunc.hpp"

#include "CliFuncs/CreditsFunc.hpp"
#include "CliFuncs/EulerPrintFunc.hpp"
#include "CliFuncs/HelpFunc.hpp"
#include "CliFuncs/PrintFunc.hpp"
#include "CliFuncs/QuitFunc.hpp"