var namespace_catch =
[
    [ "Detail", "d0/dad/namespace_catch_1_1_detail.html", "d0/dad/namespace_catch_1_1_detail" ],
    [ "Generators", "dd/d7f/namespace_catch_1_1_generators.html", "dd/d7f/namespace_catch_1_1_generators" ],
    [ "Matchers", "d2/d95/namespace_catch_1_1_matchers.html", "d2/d95/namespace_catch_1_1_matchers" ],
    [ "always_false", "d1/da0/struct_catch_1_1always__false.html", null ],
    [ "AssertionHandler", "d9/dc9/class_catch_1_1_assertion_handler.html", "d9/dc9/class_catch_1_1_assertion_handler" ],
    [ "AssertionInfo", "d4/d90/struct_catch_1_1_assertion_info.html", "d4/d90/struct_catch_1_1_assertion_info" ],
    [ "AssertionReaction", "d6/d68/struct_catch_1_1_assertion_reaction.html", "d6/d68/struct_catch_1_1_assertion_reaction" ],
    [ "AutoReg", "d4/d92/struct_catch_1_1_auto_reg.html", "d4/d92/struct_catch_1_1_auto_reg" ],
    [ "BinaryExpr", "db/dc7/class_catch_1_1_binary_expr.html", "db/dc7/class_catch_1_1_binary_expr" ],
    [ "Capturer", "dd/d86/class_catch_1_1_capturer.html", "dd/d86/class_catch_1_1_capturer" ],
    [ "CaseSensitive", "dc/d75/struct_catch_1_1_case_sensitive.html", "dc/d75/struct_catch_1_1_case_sensitive" ],
    [ "Counts", "de/d8f/struct_catch_1_1_counts.html", "de/d8f/struct_catch_1_1_counts" ],
    [ "Decomposer", "da/d49/struct_catch_1_1_decomposer.html", "da/d49/struct_catch_1_1_decomposer" ],
    [ "ExceptionTranslatorRegistrar", "d0/dd3/class_catch_1_1_exception_translator_registrar.html", "d0/dd3/class_catch_1_1_exception_translator_registrar" ],
    [ "ExprLhs", "d0/d30/class_catch_1_1_expr_lhs.html", "d0/d30/class_catch_1_1_expr_lhs" ],
    [ "GeneratorException", "dc/d8e/class_catch_1_1_generator_exception.html", "dc/d8e/class_catch_1_1_generator_exception" ],
    [ "IConfig", "dc/d57/struct_catch_1_1_i_config.html", "dc/d57/struct_catch_1_1_i_config" ],
    [ "IContext", "d1/daf/struct_catch_1_1_i_context.html", "d1/daf/struct_catch_1_1_i_context" ],
    [ "IExceptionTranslator", "db/d6d/struct_catch_1_1_i_exception_translator.html", "db/d6d/struct_catch_1_1_i_exception_translator" ],
    [ "IExceptionTranslatorRegistry", "d4/dd5/struct_catch_1_1_i_exception_translator_registry.html", "d4/dd5/struct_catch_1_1_i_exception_translator_registry" ],
    [ "IGeneratorTracker", "dd/dbf/struct_catch_1_1_i_generator_tracker.html", "dd/dbf/struct_catch_1_1_i_generator_tracker" ],
    [ "IMutableContext", "dc/d78/struct_catch_1_1_i_mutable_context.html", "dc/d78/struct_catch_1_1_i_mutable_context" ],
    [ "IMutableEnumValuesRegistry", "d3/d16/struct_catch_1_1_i_mutable_enum_values_registry.html", "d3/d16/struct_catch_1_1_i_mutable_enum_values_registry" ],
    [ "IMutableRegistryHub", "d8/d9e/struct_catch_1_1_i_mutable_registry_hub.html", "d8/d9e/struct_catch_1_1_i_mutable_registry_hub" ],
    [ "IRegistryHub", "d6/d0d/struct_catch_1_1_i_registry_hub.html", "d6/d0d/struct_catch_1_1_i_registry_hub" ],
    [ "IResultCapture", "db/d82/struct_catch_1_1_i_result_capture.html", "db/d82/struct_catch_1_1_i_result_capture" ],
    [ "IRunner", "db/dd9/struct_catch_1_1_i_runner.html", "db/dd9/struct_catch_1_1_i_runner" ],
    [ "is_callable", "d5/dd5/struct_catch_1_1is__callable.html", null ],
    [ "is_callable< Fun(Args...)>", "d2/dcb/struct_catch_1_1is__callable_3_01_fun_07_args_8_8_8_08_4.html", null ],
    [ "is_callable_tester", "d8/d50/struct_catch_1_1is__callable__tester.html", null ],
    [ "is_range", "d3/ded/struct_catch_1_1is__range.html", null ],
    [ "IStream", "d1/def/struct_catch_1_1_i_stream.html", "d1/def/struct_catch_1_1_i_stream" ],
    [ "ITestCaseRegistry", "d3/dd5/struct_catch_1_1_i_test_case_registry.html", "d3/dd5/struct_catch_1_1_i_test_case_registry" ],
    [ "ITestInvoker", "d5/d77/struct_catch_1_1_i_test_invoker.html", "d5/d77/struct_catch_1_1_i_test_invoker" ],
    [ "ITransientExpression", "d3/de5/struct_catch_1_1_i_transient_expression.html", "d3/de5/struct_catch_1_1_i_transient_expression" ],
    [ "LazyExpression", "d6/d03/class_catch_1_1_lazy_expression.html", "d6/d03/class_catch_1_1_lazy_expression" ],
    [ "MatchExpr", "dc/d6f/class_catch_1_1_match_expr.html", "dc/d6f/class_catch_1_1_match_expr" ],
    [ "MessageBuilder", "da/ddb/struct_catch_1_1_message_builder.html", "da/ddb/struct_catch_1_1_message_builder" ],
    [ "MessageInfo", "db/d87/struct_catch_1_1_message_info.html", "db/d87/struct_catch_1_1_message_info" ],
    [ "MessageStream", "d4/df1/struct_catch_1_1_message_stream.html", "d4/df1/struct_catch_1_1_message_stream" ],
    [ "NameAndTags", "d2/dc5/struct_catch_1_1_name_and_tags.html", "d2/dc5/struct_catch_1_1_name_and_tags" ],
    [ "NonCopyable", "d8/d09/class_catch_1_1_non_copyable.html", "d8/d09/class_catch_1_1_non_copyable" ],
    [ "not_this_one", "d0/d96/struct_catch_1_1not__this__one.html", null ],
    [ "Option", "df/da2/class_catch_1_1_option.html", "df/da2/class_catch_1_1_option" ],
    [ "pluralise", "df/dc0/struct_catch_1_1pluralise.html", "df/dc0/struct_catch_1_1pluralise" ],
    [ "RegistrarForTagAliases", "d7/d9b/struct_catch_1_1_registrar_for_tag_aliases.html", "d7/d9b/struct_catch_1_1_registrar_for_tag_aliases" ],
    [ "ResultDisposition", "d8/dfd/struct_catch_1_1_result_disposition.html", "d8/dfd/struct_catch_1_1_result_disposition" ],
    [ "ResultWas", "d1/d43/struct_catch_1_1_result_was.html", "d1/d43/struct_catch_1_1_result_was" ],
    [ "ReusableStringStream", "d5/ddd/class_catch_1_1_reusable_string_stream.html", "d5/ddd/class_catch_1_1_reusable_string_stream" ],
    [ "RunTests", "d3/dd6/struct_catch_1_1_run_tests.html", "d3/dd6/struct_catch_1_1_run_tests" ],
    [ "ScopedMessage", "d4/d3e/class_catch_1_1_scoped_message.html", "d4/d3e/class_catch_1_1_scoped_message" ],
    [ "Section", "db/dc8/class_catch_1_1_section.html", "db/dc8/class_catch_1_1_section" ],
    [ "SectionEndInfo", "d7/d31/struct_catch_1_1_section_end_info.html", "d7/d31/struct_catch_1_1_section_end_info" ],
    [ "SectionInfo", "db/d6f/struct_catch_1_1_section_info.html", "db/d6f/struct_catch_1_1_section_info" ],
    [ "ShowDurations", "d4/dbf/struct_catch_1_1_show_durations.html", "d4/dbf/struct_catch_1_1_show_durations" ],
    [ "SimplePcg32", "d8/d73/class_catch_1_1_simple_pcg32.html", "d8/d73/class_catch_1_1_simple_pcg32" ],
    [ "SourceLineInfo", "df/dc5/struct_catch_1_1_source_line_info.html", "df/dc5/struct_catch_1_1_source_line_info" ],
    [ "StreamEndStop", "de/d32/struct_catch_1_1_stream_end_stop.html", "de/d32/struct_catch_1_1_stream_end_stop" ],
    [ "StringMaker", "db/daf/struct_catch_1_1_string_maker.html", null ],
    [ "StringMaker< bool >", "d0/d9a/struct_catch_1_1_string_maker_3_01bool_01_4.html", null ],
    [ "StringMaker< Catch::Detail::Approx >", "d0/d4c/struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html", null ],
    [ "StringMaker< char * >", "d4/d3d/struct_catch_1_1_string_maker_3_01char_01_5_01_4.html", null ],
    [ "StringMaker< char >", "d0/d87/struct_catch_1_1_string_maker_3_01char_01_4.html", null ],
    [ "StringMaker< char const * >", "db/dce/struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html", null ],
    [ "StringMaker< char[SZ]>", "d0/d48/struct_catch_1_1_string_maker_3_01char[_s_z]_4.html", null ],
    [ "StringMaker< double >", "de/dc1/struct_catch_1_1_string_maker_3_01double_01_4.html", null ],
    [ "StringMaker< float >", "d0/d1a/struct_catch_1_1_string_maker_3_01float_01_4.html", null ],
    [ "StringMaker< int >", "d6/d1f/struct_catch_1_1_string_maker_3_01int_01_4.html", null ],
    [ "StringMaker< long >", "da/dc5/struct_catch_1_1_string_maker_3_01long_01_4.html", null ],
    [ "StringMaker< long long >", "d9/d67/struct_catch_1_1_string_maker_3_01long_01long_01_4.html", null ],
    [ "StringMaker< R C::* >", "d2/da4/struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html", null ],
    [ "StringMaker< R, typename std::enable_if< is_range< R >::value &&!::Catch::Detail::IsStreamInsertable< R >::value >::type >", "d9/d3a/struct_catch_1_1_string_maker_3_01_r_00_01typename_01std_1_1enable__if_3_01is__range_3_01_r_01_4536d8fedfff6d62432b3dc59b56e1380.html", null ],
    [ "StringMaker< signed char >", "d9/d4e/struct_catch_1_1_string_maker_3_01signed_01char_01_4.html", null ],
    [ "StringMaker< signed char[SZ]>", "d9/dae/struct_catch_1_1_string_maker_3_01signed_01char[_s_z]_4.html", null ],
    [ "StringMaker< std::nullptr_t >", "d6/de8/struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html", null ],
    [ "StringMaker< std::string >", "db/d4c/struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html", null ],
    [ "StringMaker< std::wstring >", "d8/d73/struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html", null ],
    [ "StringMaker< T * >", "de/dc1/struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html", null ],
    [ "StringMaker< T[SZ]>", "d7/d54/struct_catch_1_1_string_maker_3_01_t[_s_z]_4.html", null ],
    [ "StringMaker< unsigned char >", "db/d19/struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html", null ],
    [ "StringMaker< unsigned char[SZ]>", "d1/da7/struct_catch_1_1_string_maker_3_01unsigned_01char[_s_z]_4.html", null ],
    [ "StringMaker< unsigned int >", "d4/dc9/struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html", null ],
    [ "StringMaker< unsigned long >", "d4/ddf/struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html", null ],
    [ "StringMaker< unsigned long long >", "db/d5e/struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html", null ],
    [ "StringMaker< wchar_t * >", "df/d91/struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html", null ],
    [ "StringMaker< wchar_t const * >", "dd/d07/struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html", null ],
    [ "StringRef", "dd/d6c/class_catch_1_1_string_ref.html", "dd/d6c/class_catch_1_1_string_ref" ],
    [ "TestCase", "d5/d5a/class_catch_1_1_test_case.html", "d5/d5a/class_catch_1_1_test_case" ],
    [ "TestCaseInfo", "d1/d61/struct_catch_1_1_test_case_info.html", "d1/d61/struct_catch_1_1_test_case_info" ],
    [ "TestFailureException", "d3/ddd/struct_catch_1_1_test_failure_exception.html", null ],
    [ "TestInvokerAsMethod", "d1/d27/class_catch_1_1_test_invoker_as_method.html", "d1/d27/class_catch_1_1_test_invoker_as_method" ],
    [ "Timer", "d6/d37/class_catch_1_1_timer.html", "d6/d37/class_catch_1_1_timer" ],
    [ "Totals", "d4/da0/struct_catch_1_1_totals.html", "d4/da0/struct_catch_1_1_totals" ],
    [ "true_given", "d0/da9/struct_catch_1_1true__given.html", null ],
    [ "UnaryExpr", "d7/da1/class_catch_1_1_unary_expr.html", "d7/da1/class_catch_1_1_unary_expr" ],
    [ "UseColour", "d6/d9f/struct_catch_1_1_use_colour.html", "d6/d9f/struct_catch_1_1_use_colour" ],
    [ "WaitForKeypress", "de/def/struct_catch_1_1_wait_for_keypress.html", "de/def/struct_catch_1_1_wait_for_keypress" ],
    [ "WarnAbout", "db/d49/struct_catch_1_1_warn_about.html", "db/d49/struct_catch_1_1_warn_about" ]
];